/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChangePasswordRequest,
    ChangePasswordRequestFromJSON,
    ChangePasswordRequestToJSON,
} from '../models/ChangePasswordRequest';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type TokenRefresh,
    TokenRefreshFromJSON,
    TokenRefreshToJSON,
} from '../models/TokenRefresh';
import {
    type TokenResponse,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/TokenResponse';
import {
    type UserCreate,
    UserCreateFromJSON,
    UserCreateToJSON,
} from '../models/UserCreate';
import {
    type UserLogin,
    UserLoginFromJSON,
    UserLoginToJSON,
} from '../models/UserLogin';
import {
    type UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/UserResponse';
import {
    type UserUpdate,
    UserUpdateFromJSON,
    UserUpdateToJSON,
} from '../models/UserUpdate';

export interface ChangePasswordV1AuthChangePasswordPostRequest {
    changePasswordRequest: ChangePasswordRequest;
}

export interface LoginV1AuthLoginPostRequest {
    userLogin: UserLogin;
}

export interface RefreshV1AuthRefreshPostRequest {
    tokenRefresh: TokenRefresh;
}

export interface RegisterV1AuthRegisterPostRequest {
    userCreate: UserCreate;
}

export interface UpdateMeV1AuthMePatchRequest {
    userUpdate: UserUpdate;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for changePasswordV1AuthChangePasswordPost without sending the request
     */
    async changePasswordV1AuthChangePasswordPostRequestOpts(requestParameters: ChangePasswordV1AuthChangePasswordPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['changePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'changePasswordRequest',
                'Required parameter "changePasswordRequest" was null or undefined when calling changePasswordV1AuthChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestToJSON(requestParameters['changePasswordRequest']),
        };
    }

    /**
     * Change Password
     */
    async changePasswordV1AuthChangePasswordPostRaw(requestParameters: ChangePasswordV1AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.changePasswordV1AuthChangePasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change Password
     */
    async changePasswordV1AuthChangePasswordPost(requestParameters: ChangePasswordV1AuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changePasswordV1AuthChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMeV1AuthMeDelete without sending the request
     */
    async deleteMeV1AuthMeDeleteRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/me`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Me
     */
    async deleteMeV1AuthMeDeleteRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMeV1AuthMeDeleteRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Me
     */
    async deleteMeV1AuthMeDelete(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMeV1AuthMeDeleteRaw(initOverrides);
    }

    /**
     * Creates request options for loginV1AuthLoginPost without sending the request
     */
    async loginV1AuthLoginPostRequestOpts(requestParameters: LoginV1AuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userLogin'] == null) {
            throw new runtime.RequiredError(
                'userLogin',
                'Required parameter "userLogin" was null or undefined when calling loginV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginToJSON(requestParameters['userLogin']),
        };
    }

    /**
     * Login
     */
    async loginV1AuthLoginPostRaw(requestParameters: LoginV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.loginV1AuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Login
     */
    async loginV1AuthLoginPost(requestParameters: LoginV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.loginV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for meV1AuthMeGet without sending the request
     */
    async meV1AuthMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Me
     */
    async meV1AuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.meV1AuthMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Me
     */
    async meV1AuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.meV1AuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for refreshV1AuthRefreshPost without sending the request
     */
    async refreshV1AuthRefreshPostRequestOpts(requestParameters: RefreshV1AuthRefreshPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenRefresh'] == null) {
            throw new runtime.RequiredError(
                'tokenRefresh',
                'Required parameter "tokenRefresh" was null or undefined when calling refreshV1AuthRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshToJSON(requestParameters['tokenRefresh']),
        };
    }

    /**
     * Refresh
     */
    async refreshV1AuthRefreshPostRaw(requestParameters: RefreshV1AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.refreshV1AuthRefreshPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Refresh
     */
    async refreshV1AuthRefreshPost(requestParameters: RefreshV1AuthRefreshPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.refreshV1AuthRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerV1AuthRegisterPost without sending the request
     */
    async registerV1AuthRegisterPostRequestOpts(requestParameters: RegisterV1AuthRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userCreate'] == null) {
            throw new runtime.RequiredError(
                'userCreate',
                'Required parameter "userCreate" was null or undefined when calling registerV1AuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateToJSON(requestParameters['userCreate']),
        };
    }

    /**
     * Register
     */
    async registerV1AuthRegisterPostRaw(requestParameters: RegisterV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.registerV1AuthRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Register
     */
    async registerV1AuthRegisterPost(requestParameters: RegisterV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.registerV1AuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateMeV1AuthMePatch without sending the request
     */
    async updateMeV1AuthMePatchRequestOpts(requestParameters: UpdateMeV1AuthMePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userUpdate'] == null) {
            throw new runtime.RequiredError(
                'userUpdate',
                'Required parameter "userUpdate" was null or undefined when calling updateMeV1AuthMePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/me`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateToJSON(requestParameters['userUpdate']),
        };
    }

    /**
     * Update Me
     */
    async updateMeV1AuthMePatchRaw(requestParameters: UpdateMeV1AuthMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.updateMeV1AuthMePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Update Me
     */
    async updateMeV1AuthMePatch(requestParameters: UpdateMeV1AuthMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.updateMeV1AuthMePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
