/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CheckoutResponse,
    CheckoutResponseFromJSON,
    CheckoutResponseToJSON,
} from '../models/CheckoutResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type PlanResponse,
    PlanResponseFromJSON,
    PlanResponseToJSON,
} from '../models/PlanResponse';
import {
    type PortalResponse,
    PortalResponseFromJSON,
    PortalResponseToJSON,
} from '../models/PortalResponse';

export interface CheckoutV1BillingCheckoutPostRequest {
    priceId: string;
}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Creates request options for checkoutV1BillingCheckoutPost without sending the request
     */
    async checkoutV1BillingCheckoutPostRequestOpts(requestParameters: CheckoutV1BillingCheckoutPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling checkoutV1BillingCheckoutPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['priceId'] != null) {
            queryParameters['price_id'] = requestParameters['priceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Checkout
     */
    async checkoutV1BillingCheckoutPostRaw(requestParameters: CheckoutV1BillingCheckoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutResponse>> {
        const requestOptions = await this.checkoutV1BillingCheckoutPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutResponseFromJSON(jsonValue));
    }

    /**
     * Checkout
     */
    async checkoutV1BillingCheckoutPost(requestParameters: CheckoutV1BillingCheckoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutResponse> {
        const response = await this.checkoutV1BillingCheckoutPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPlanV1BillingPlanGet without sending the request
     */
    async getPlanV1BillingPlanGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/plan`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Plan
     */
    async getPlanV1BillingPlanGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PlanResponse>>> {
        const requestOptions = await this.getPlanV1BillingPlanGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlanResponseFromJSON));
    }

    /**
     * Get Plan
     */
    async getPlanV1BillingPlanGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PlanResponse>> {
        const response = await this.getPlanV1BillingPlanGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for portalV1BillingPortalPost without sending the request
     */
    async portalV1BillingPortalPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/billing/portal`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Portal
     */
    async portalV1BillingPortalPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortalResponse>> {
        const requestOptions = await this.portalV1BillingPortalPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortalResponseFromJSON(jsonValue));
    }

    /**
     * Portal
     */
    async portalV1BillingPortalPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortalResponse> {
        const response = await this.portalV1BillingPortalPostRaw(initOverrides);
        return await response.value();
    }

}
