/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConnectorCreate,
    ConnectorCreateFromJSON,
    ConnectorCreateToJSON,
} from '../models/ConnectorCreate';
import {
    type ConnectorResponse,
    ConnectorResponseFromJSON,
    ConnectorResponseToJSON,
} from '../models/ConnectorResponse';
import {
    type ConnectorTestRequest,
    ConnectorTestRequestFromJSON,
    ConnectorTestRequestToJSON,
} from '../models/ConnectorTestRequest';
import {
    type ConnectorTestResponse,
    ConnectorTestResponseFromJSON,
    ConnectorTestResponseToJSON,
} from '../models/ConnectorTestResponse';
import {
    type ConnectorUpdate,
    ConnectorUpdateFromJSON,
    ConnectorUpdateToJSON,
} from '../models/ConnectorUpdate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateConnectorV1ConnectorsPostRequest {
    connectorCreate: ConnectorCreate;
}

export interface DeleteConnectorV1ConnectorsConnectorIdDeleteRequest {
    connectorId: string;
}

export interface GetConnectorV1ConnectorsConnectorIdGetRequest {
    connectorId: string;
}

export interface SyncConnectorV1ConnectorsConnectorIdSyncPostRequest {
    connectorId: string;
}

export interface TestConnectorV1ConnectorsTestPostRequest {
    connectorTestRequest: ConnectorTestRequest;
}

export interface UpdateConnectorV1ConnectorsConnectorIdPatchRequest {
    connectorId: string;
    connectorUpdate: ConnectorUpdate;
}

/**
 * 
 */
export class ConnectorsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createConnectorV1ConnectorsPost without sending the request
     */
    async createConnectorV1ConnectorsPostRequestOpts(requestParameters: CreateConnectorV1ConnectorsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorCreate'] == null) {
            throw new runtime.RequiredError(
                'connectorCreate',
                'Required parameter "connectorCreate" was null or undefined when calling createConnectorV1ConnectorsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectorCreateToJSON(requestParameters['connectorCreate']),
        };
    }

    /**
     * Create Connector
     */
    async createConnectorV1ConnectorsPostRaw(requestParameters: CreateConnectorV1ConnectorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectorResponse>> {
        const requestOptions = await this.createConnectorV1ConnectorsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorResponseFromJSON(jsonValue));
    }

    /**
     * Create Connector
     */
    async createConnectorV1ConnectorsPost(requestParameters: CreateConnectorV1ConnectorsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectorResponse> {
        const response = await this.createConnectorV1ConnectorsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteConnectorV1ConnectorsConnectorIdDelete without sending the request
     */
    async deleteConnectorV1ConnectorsConnectorIdDeleteRequestOpts(requestParameters: DeleteConnectorV1ConnectorsConnectorIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorId'] == null) {
            throw new runtime.RequiredError(
                'connectorId',
                'Required parameter "connectorId" was null or undefined when calling deleteConnectorV1ConnectorsConnectorIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/{connector_id}`;
        urlPath = urlPath.replace('{connector_id}', encodeURIComponent(String(requestParameters['connectorId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Connector
     */
    async deleteConnectorV1ConnectorsConnectorIdDeleteRaw(requestParameters: DeleteConnectorV1ConnectorsConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteConnectorV1ConnectorsConnectorIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Connector
     */
    async deleteConnectorV1ConnectorsConnectorIdDelete(requestParameters: DeleteConnectorV1ConnectorsConnectorIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConnectorV1ConnectorsConnectorIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getConnectorV1ConnectorsConnectorIdGet without sending the request
     */
    async getConnectorV1ConnectorsConnectorIdGetRequestOpts(requestParameters: GetConnectorV1ConnectorsConnectorIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorId'] == null) {
            throw new runtime.RequiredError(
                'connectorId',
                'Required parameter "connectorId" was null or undefined when calling getConnectorV1ConnectorsConnectorIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/{connector_id}`;
        urlPath = urlPath.replace('{connector_id}', encodeURIComponent(String(requestParameters['connectorId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Connector
     */
    async getConnectorV1ConnectorsConnectorIdGetRaw(requestParameters: GetConnectorV1ConnectorsConnectorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectorResponse>> {
        const requestOptions = await this.getConnectorV1ConnectorsConnectorIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorResponseFromJSON(jsonValue));
    }

    /**
     * Get Connector
     */
    async getConnectorV1ConnectorsConnectorIdGet(requestParameters: GetConnectorV1ConnectorsConnectorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectorResponse> {
        const response = await this.getConnectorV1ConnectorsConnectorIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listConnectorsV1ConnectorsGet without sending the request
     */
    async listConnectorsV1ConnectorsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Connectors
     */
    async listConnectorsV1ConnectorsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConnectorResponse>>> {
        const requestOptions = await this.listConnectorsV1ConnectorsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConnectorResponseFromJSON));
    }

    /**
     * List Connectors
     */
    async listConnectorsV1ConnectorsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConnectorResponse>> {
        const response = await this.listConnectorsV1ConnectorsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syncConnectorV1ConnectorsConnectorIdSyncPost without sending the request
     */
    async syncConnectorV1ConnectorsConnectorIdSyncPostRequestOpts(requestParameters: SyncConnectorV1ConnectorsConnectorIdSyncPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorId'] == null) {
            throw new runtime.RequiredError(
                'connectorId',
                'Required parameter "connectorId" was null or undefined when calling syncConnectorV1ConnectorsConnectorIdSyncPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/{connector_id}/sync`;
        urlPath = urlPath.replace('{connector_id}', encodeURIComponent(String(requestParameters['connectorId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sync Connector
     */
    async syncConnectorV1ConnectorsConnectorIdSyncPostRaw(requestParameters: SyncConnectorV1ConnectorsConnectorIdSyncPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.syncConnectorV1ConnectorsConnectorIdSyncPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Sync Connector
     */
    async syncConnectorV1ConnectorsConnectorIdSyncPost(requestParameters: SyncConnectorV1ConnectorsConnectorIdSyncPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.syncConnectorV1ConnectorsConnectorIdSyncPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testConnectorV1ConnectorsTestPost without sending the request
     */
    async testConnectorV1ConnectorsTestPostRequestOpts(requestParameters: TestConnectorV1ConnectorsTestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorTestRequest'] == null) {
            throw new runtime.RequiredError(
                'connectorTestRequest',
                'Required parameter "connectorTestRequest" was null or undefined when calling testConnectorV1ConnectorsTestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/test`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectorTestRequestToJSON(requestParameters['connectorTestRequest']),
        };
    }

    /**
     * Test a database connection without creating a connector.
     * Test Connector
     */
    async testConnectorV1ConnectorsTestPostRaw(requestParameters: TestConnectorV1ConnectorsTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectorTestResponse>> {
        const requestOptions = await this.testConnectorV1ConnectorsTestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorTestResponseFromJSON(jsonValue));
    }

    /**
     * Test a database connection without creating a connector.
     * Test Connector
     */
    async testConnectorV1ConnectorsTestPost(requestParameters: TestConnectorV1ConnectorsTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectorTestResponse> {
        const response = await this.testConnectorV1ConnectorsTestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateConnectorV1ConnectorsConnectorIdPatch without sending the request
     */
    async updateConnectorV1ConnectorsConnectorIdPatchRequestOpts(requestParameters: UpdateConnectorV1ConnectorsConnectorIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectorId'] == null) {
            throw new runtime.RequiredError(
                'connectorId',
                'Required parameter "connectorId" was null or undefined when calling updateConnectorV1ConnectorsConnectorIdPatch().'
            );
        }

        if (requestParameters['connectorUpdate'] == null) {
            throw new runtime.RequiredError(
                'connectorUpdate',
                'Required parameter "connectorUpdate" was null or undefined when calling updateConnectorV1ConnectorsConnectorIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/{connector_id}`;
        urlPath = urlPath.replace('{connector_id}', encodeURIComponent(String(requestParameters['connectorId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectorUpdateToJSON(requestParameters['connectorUpdate']),
        };
    }

    /**
     * Update Connector
     */
    async updateConnectorV1ConnectorsConnectorIdPatchRaw(requestParameters: UpdateConnectorV1ConnectorsConnectorIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectorResponse>> {
        const requestOptions = await this.updateConnectorV1ConnectorsConnectorIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectorResponseFromJSON(jsonValue));
    }

    /**
     * Update Connector
     */
    async updateConnectorV1ConnectorsConnectorIdPatch(requestParameters: UpdateConnectorV1ConnectorsConnectorIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectorResponse> {
        const response = await this.updateConnectorV1ConnectorsConnectorIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
