/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DashboardStats,
    DashboardStatsFromJSON,
    DashboardStatsToJSON,
} from '../models/DashboardStats';

/**
 * 
 */
export class DashboardApi extends runtime.BaseAPI {

    /**
     * Creates request options for dashboardStatsV1DashboardStatsGet without sending the request
     */
    async dashboardStatsV1DashboardStatsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/dashboard/stats`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Dashboard Stats
     */
    async dashboardStatsV1DashboardStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardStats>> {
        const requestOptions = await this.dashboardStatsV1DashboardStatsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DashboardStatsFromJSON(jsonValue));
    }

    /**
     * Dashboard Stats
     */
    async dashboardStatsV1DashboardStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardStats> {
        const response = await this.dashboardStatsV1DashboardStatsGetRaw(initOverrides);
        return await response.value();
    }

}
