/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type PaginatedQueries,
    PaginatedQueriesFromJSON,
    PaginatedQueriesToJSON,
} from '../models/PaginatedQueries';
import {
    type QueryRequest,
    QueryRequestFromJSON,
    QueryRequestToJSON,
} from '../models/QueryRequest';
import {
    type QueryResponse,
    QueryResponseFromJSON,
    QueryResponseToJSON,
} from '../models/QueryResponse';

export interface CreateQueryV1QueriesPostRequest {
    queryRequest: QueryRequest;
}

export interface GetQueryV1QueriesQueryIdGetRequest {
    queryId: string;
}

export interface ListQueriesV1QueriesGetRequest {
    page?: number;
    perPage?: number;
}

/**
 * 
 */
export class QueriesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createQueryV1QueriesPost without sending the request
     */
    async createQueryV1QueriesPostRequestOpts(requestParameters: CreateQueryV1QueriesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['queryRequest'] == null) {
            throw new runtime.RequiredError(
                'queryRequest',
                'Required parameter "queryRequest" was null or undefined when calling createQueryV1QueriesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QueryRequestToJSON(requestParameters['queryRequest']),
        };
    }

    /**
     * Create Query
     */
    async createQueryV1QueriesPostRaw(requestParameters: CreateQueryV1QueriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        const requestOptions = await this.createQueryV1QueriesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Create Query
     */
    async createQueryV1QueriesPost(requestParameters: CreateQueryV1QueriesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.createQueryV1QueriesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getQueryV1QueriesQueryIdGet without sending the request
     */
    async getQueryV1QueriesQueryIdGetRequestOpts(requestParameters: GetQueryV1QueriesQueryIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['queryId'] == null) {
            throw new runtime.RequiredError(
                'queryId',
                'Required parameter "queryId" was null or undefined when calling getQueryV1QueriesQueryIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries/{query_id}`;
        urlPath = urlPath.replace('{query_id}', encodeURIComponent(String(requestParameters['queryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Query
     */
    async getQueryV1QueriesQueryIdGetRaw(requestParameters: GetQueryV1QueriesQueryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueryResponse>> {
        const requestOptions = await this.getQueryV1QueriesQueryIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueryResponseFromJSON(jsonValue));
    }

    /**
     * Get Query
     */
    async getQueryV1QueriesQueryIdGet(requestParameters: GetQueryV1QueriesQueryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueryResponse> {
        const response = await this.getQueryV1QueriesQueryIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listQueriesV1QueriesGet without sending the request
     */
    async listQueriesV1QueriesGetRequestOpts(requestParameters: ListQueriesV1QueriesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/queries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Queries
     */
    async listQueriesV1QueriesGetRaw(requestParameters: ListQueriesV1QueriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedQueries>> {
        const requestOptions = await this.listQueriesV1QueriesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedQueriesFromJSON(jsonValue));
    }

    /**
     * List Queries
     */
    async listQueriesV1QueriesGet(requestParameters: ListQueriesV1QueriesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedQueries> {
        const response = await this.listQueriesV1QueriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
