/**
 * Auto-generated by openapi-typescript.
 * Do not edit directly — regenerate with: make generate
 */

import createClient from "openapi-fetch";
import type { paths } from "./api-types";

export interface CreateClientOptions {
  baseUrl: string;
  accessToken?: string;
  fetch?: typeof fetch;
}

export function createEasySQLClient(options: CreateClientOptions) {
  const client = createClient<paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
    headers: options.accessToken
      ? { Authorization: `Bearer ${options.accessToken}` }
      : {},
  });

  return {
{{METHODS}}
  };
}

export type EasySQLClient = ReturnType<typeof createEasySQLClient>;
