import "dotenv/config";
import openapiTS from "openapi-typescript";

const apiUrl = process.env.EASYSQL_API_URL;

if (!apiUrl) {
  console.error("❌ EASYSQL_API_URL is not set.");
  console.error("   Copy .env.example to .env and fill in the API URL.");
  process.exit(1);
}

const specUrl = `${apiUrl.replace(/\/+$/, "")}/openapi.json`;

// ─── 1. Generate api-types.ts ───────────────────────────────────────

console.log(`🔽 Downloading spec from: ${specUrl}`);

const [typesOutput] = await Promise.all([
  openapiTS(specUrl),
  generateClient(specUrl),
]);

await Bun.write("src/api-types.ts", typesOutput);

// ─── 2. Generate client.ts ──────────────────────────────────────────

async function generateClient(url: string) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch spec: ${response.status}`);
  }
  const spec = await response.json();

  const methods = extractMethods(spec);
  const clientCode = buildClientFile(methods);

  await Bun.write("src/client.ts", clientCode);
  console.log("✅ src/client.ts generated successfully.");
}

// ─── 3. Extract methods from spec ───────────────────────────────────

interface GeneratedMethod {
  name: string;
  path: string;
  httpMethod: string;
  hasBody: boolean;
  hasPathParams: boolean;
  hasQueryParams: boolean;
  pathSignature: string; // e.g. '"/v1/auth/login"' or '"/v1/connectors/{connector_id}"'
  typeSignature: string; // e.g. 'paths["/v1/auth/login"]["post"]'
}

function extractMethods(spec: any): GeneratedMethod[] {
  const methods: GeneratedMethod[] = [];

  for (const [path, pathItem] of Object.entries(
    spec.paths as Record<string, any>,
  )) {
    for (const httpMethod of [
      "get",
      "post",
      "put",
      "patch",
      "delete",
    ] as const) {
      const operation = (pathItem as any)[httpMethod];
      if (!operation) continue;

      const operationId: string = operation.operationId;
      const methodName = deriveMethodName(operationId, httpMethod, path);
      const hasBody = !!operation.requestBody;
      const hasPathParams = path.includes("{");
      const hasQueryParams =
        (operation.parameters as any[])?.some((p: any) => p.in === "query") ??
        false;

      const pathSignature = `"${path}"`;
      const typeSignature = `paths${path
        .split("/")
        .map((seg) => `["${seg}"]`)
        .join("")}["${httpMethod}"]`;

      methods.push({
        name: methodName,
        path,
        httpMethod,
        hasBody,
        hasPathParams,
        hasQueryParams,
        pathSignature,
        typeSignature,
      });
    }
  }

  // Deduplicate method names by appending path context
  const nameCounts = new Map<string, number>();
  for (const m of methods) {
    nameCounts.set(m.name, (nameCounts.get(m.name) ?? 0) + 1);
  }

  for (const m of methods) {
    if ((nameCounts.get(m.name) ?? 0) > 1) {
      // Append HTTP method to disambiguate
      m.name = `${m.name}_${m.httpMethod}`;
    }
  }

  return methods;
}

function deriveMethodName(
  operationId: string,
  httpMethod: string,
  _path: string,
): string {
  // Remove trailing HTTP method (e.g. "_post", "_get")
  const withoutMethod = operationId.replace(new RegExp(`_${httpMethod}$`), "");

  // Find version marker "_v" followed by digits and take everything before it
  const versionMatch = withoutMethod.match(/_v\d+_/);
  const action = versionMatch
    ? withoutMethod.substring(0, versionMatch.index!)
    : withoutMethod;

  // Convert snake_case to camelCase
  return action.replace(/_([a-z])/g, (_: string, c: string) => c.toUpperCase());
}

// ─── 4. Build client.ts file ────────────────────────────────────────

function buildClientFile(methods: GeneratedMethod[]): string {
  const methodCode = methods.map(buildMethod).join(",\n\n  ");

  return `/**
 * Auto-generated by openapi-typescript.
 * Do not edit directly — regenerate with: make generate
 */

import createClient from "openapi-fetch";
import type { paths } from "./api-types";

export interface CreateClientOptions {
  baseUrl: string;
  accessToken?: string;
  fetch?: typeof fetch;
}

export function createEasySQLClient(options: CreateClientOptions) {
  const client = createClient<paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
    headers: options.accessToken
      ? { Authorization: \`Bearer \${options.accessToken}\` }
      : {},
  });

  return {
${methodCode}
  };
}

export type EasySQLClient = ReturnType<typeof createEasySQLClient>;
`;
}

function buildMethod(m: GeneratedMethod): string {
  const params = buildParams(m);
  const args = buildArgs(m);
  const methodCall = `client.${m.httpMethod.toUpperCase()}(${m.pathSignature}${args})`;

  return `  /** ${m.httpMethod.toUpperCase()} ${m.path} */\n  ${m.name}(${params}) {\n    return ${methodCall};\n  }`;
}

function buildParams(m: GeneratedMethod): string {
  const parts: string[] = [];

  if (m.hasBody) {
    parts.push(
      `body: ${m.typeSignature}["requestBody"]["content"]["application/json"]`,
    );
  }
  if (m.hasPathParams || m.hasQueryParams) {
    const paramParts: string[] = [];
    if (m.hasPathParams)
      paramParts.push(`path: ${m.typeSignature}["parameters"]["path"]`);
    if (m.hasQueryParams)
      paramParts.push(`query: ${m.typeSignature}["parameters"]["query"]`);
    parts.push(`params: { ${paramParts.join("; ")} }`);
  }

  return parts.join(", ");
}

function buildArgs(m: GeneratedMethod): string {
  if (!m.hasBody && !m.hasPathParams && !m.hasQueryParams) {
    return "";
  }

  const argParts: string[] = [];
  if (m.hasBody) argParts.push("body");
  if (m.hasPathParams || m.hasQueryParams) argParts.push("params");

  return `, { ${argParts.join(", ")} }`;
}

console.log("✅ src/api-types.ts generated successfully.");
