/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorConfig
 */
export interface ConnectorConfig {
    /**
     * 
     * @type {string}
     * @memberof ConnectorConfig
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectorConfig
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof ConnectorConfig
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorConfig
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorConfig
     */
    database: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConnectorConfig
     */
    ssl?: boolean;
}

/**
 * Check if a given object implements the ConnectorConfig interface.
 */
export function instanceOfConnectorConfig(value: object): value is ConnectorConfig {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('database' in value) || value['database'] === undefined) return false;
    return true;
}

export function ConnectorConfigFromJSON(json: any): ConnectorConfig {
    return ConnectorConfigFromJSONTyped(json, false);
}

export function ConnectorConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
        'user': json['user'],
        'password': json['password'],
        'database': json['database'],
        'ssl': json['ssl'] == null ? undefined : json['ssl'],
    };
}

export function ConnectorConfigToJSON(json: any): ConnectorConfig {
    return ConnectorConfigToJSONTyped(json, false);
}

export function ConnectorConfigToJSONTyped(value?: ConnectorConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'port': value['port'],
        'user': value['user'],
        'password': value['password'],
        'database': value['database'],
        'ssl': value['ssl'],
    };
}

