/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorResponse
 */
export interface ConnectorResponse {
    /**
     * 
     * @type {string}
     * @memberof ConnectorResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorResponse
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof ConnectorResponse
     */
    lastSyncAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ConnectorResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ConnectorResponse interface.
 */
export function instanceOfConnectorResponse(value: object): value is ConnectorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('lastSyncAt' in value) || value['lastSyncAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ConnectorResponseFromJSON(json: any): ConnectorResponse {
    return ConnectorResponseFromJSONTyped(json, false);
}

export function ConnectorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': json['name'],
        'lastSyncAt': (json['last_sync_at'] == null ? null : new Date(json['last_sync_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ConnectorResponseToJSON(json: any): ConnectorResponse {
    return ConnectorResponseToJSONTyped(json, false);
}

export function ConnectorResponseToJSONTyped(value?: ConnectorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'last_sync_at': value['lastSyncAt'] == null ? value['lastSyncAt'] : value['lastSyncAt'].toISOString(),
        'created_at': value['createdAt'].toISOString(),
    };
}

