/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorConfig } from './ConnectorConfig';
import {
    ConnectorConfigFromJSON,
    ConnectorConfigFromJSONTyped,
    ConnectorConfigToJSON,
    ConnectorConfigToJSONTyped,
} from './ConnectorConfig';

/**
 * 
 * @export
 * @interface ConnectorTestRequest
 */
export interface ConnectorTestRequest {
    /**
     * 
     * @type {string}
     * @memberof ConnectorTestRequest
     */
    type: string;
    /**
     * 
     * @type {ConnectorConfig}
     * @memberof ConnectorTestRequest
     */
    config: ConnectorConfig;
}

/**
 * Check if a given object implements the ConnectorTestRequest interface.
 */
export function instanceOfConnectorTestRequest(value: object): value is ConnectorTestRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function ConnectorTestRequestFromJSON(json: any): ConnectorTestRequest {
    return ConnectorTestRequestFromJSONTyped(json, false);
}

export function ConnectorTestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorTestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'config': ConnectorConfigFromJSON(json['config']),
    };
}

export function ConnectorTestRequestToJSON(json: any): ConnectorTestRequest {
    return ConnectorTestRequestToJSONTyped(json, false);
}

export function ConnectorTestRequestToJSONTyped(value?: ConnectorTestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'config': ConnectorConfigToJSON(value['config']),
    };
}

