/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorConfig } from './ConnectorConfig';
import {
    ConnectorConfigFromJSON,
    ConnectorConfigFromJSONTyped,
    ConnectorConfigToJSON,
    ConnectorConfigToJSONTyped,
} from './ConnectorConfig';

/**
 * 
 * @export
 * @interface ConnectorCreate
 */
export interface ConnectorCreate {
    /**
     * 
     * @type {string}
     * @memberof ConnectorCreate
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorCreate
     */
    name: string;
    /**
     * 
     * @type {ConnectorConfig}
     * @memberof ConnectorCreate
     */
    config: ConnectorConfig;
}

/**
 * Check if a given object implements the ConnectorCreate interface.
 */
export function instanceOfConnectorCreate(value: object): value is ConnectorCreate {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function ConnectorCreateFromJSON(json: any): ConnectorCreate {
    return ConnectorCreateFromJSONTyped(json, false);
}

export function ConnectorCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'config': ConnectorConfigFromJSON(json['config']),
    };
}

export function ConnectorCreateToJSON(json: any): ConnectorCreate {
    return ConnectorCreateToJSONTyped(json, false);
}

export function ConnectorCreateToJSONTyped(value?: ConnectorCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'config': ConnectorConfigToJSON(value['config']),
    };
}

