/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorTestResponse
 */
export interface ConnectorTestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ConnectorTestResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConnectorTestResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ConnectorTestResponse interface.
 */
export function instanceOfConnectorTestResponse(value: object): value is ConnectorTestResponse {
    return true;
}

export function ConnectorTestResponseFromJSON(json: any): ConnectorTestResponse {
    return ConnectorTestResponseFromJSONTyped(json, false);
}

export function ConnectorTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ConnectorTestResponseToJSON(json: any): ConnectorTestResponse {
    return ConnectorTestResponseToJSONTyped(json, false);
}

export function ConnectorTestResponseToJSONTyped(value?: ConnectorTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

