/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConnectorConfig } from './ConnectorConfig';
import {
    ConnectorConfigFromJSON,
    ConnectorConfigFromJSONTyped,
    ConnectorConfigToJSON,
    ConnectorConfigToJSONTyped,
} from './ConnectorConfig';

/**
 * 
 * @export
 * @interface ConnectorUpdate
 */
export interface ConnectorUpdate {
    /**
     * 
     * @type {string}
     * @memberof ConnectorUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {ConnectorConfig}
     * @memberof ConnectorUpdate
     */
    config?: ConnectorConfig | null;
}

/**
 * Check if a given object implements the ConnectorUpdate interface.
 */
export function instanceOfConnectorUpdate(value: object): value is ConnectorUpdate {
    return true;
}

export function ConnectorUpdateFromJSON(json: any): ConnectorUpdate {
    return ConnectorUpdateFromJSONTyped(json, false);
}

export function ConnectorUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'config': json['config'] == null ? undefined : ConnectorConfigFromJSON(json['config']),
    };
}

export function ConnectorUpdateToJSON(json: any): ConnectorUpdate {
    return ConnectorUpdateToJSONTyped(json, false);
}

export function ConnectorUpdateToJSONTyped(value?: ConnectorUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'config': ConnectorConfigToJSON(value['config']),
    };
}

