/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectorUsage
 */
export interface ConnectorUsage {
    /**
     * 
     * @type {string}
     * @memberof ConnectorUsage
     */
    connectorId: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectorUsage
     */
    connectorName: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectorUsage
     */
    queryCount: number;
}

/**
 * Check if a given object implements the ConnectorUsage interface.
 */
export function instanceOfConnectorUsage(value: object): value is ConnectorUsage {
    if (!('connectorId' in value) || value['connectorId'] === undefined) return false;
    if (!('connectorName' in value) || value['connectorName'] === undefined) return false;
    if (!('queryCount' in value) || value['queryCount'] === undefined) return false;
    return true;
}

export function ConnectorUsageFromJSON(json: any): ConnectorUsage {
    return ConnectorUsageFromJSONTyped(json, false);
}

export function ConnectorUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectorUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'connectorId': json['connector_id'],
        'connectorName': json['connector_name'],
        'queryCount': json['query_count'],
    };
}

export function ConnectorUsageToJSON(json: any): ConnectorUsage {
    return ConnectorUsageToJSONTyped(json, false);
}

export function ConnectorUsageToJSONTyped(value?: ConnectorUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connector_id': value['connectorId'],
        'connector_name': value['connectorName'],
        'query_count': value['queryCount'],
    };
}

