/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyQueryCount
 */
export interface DailyQueryCount {
    /**
     * 
     * @type {Date}
     * @memberof DailyQueryCount
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof DailyQueryCount
     */
    count: number;
}

/**
 * Check if a given object implements the DailyQueryCount interface.
 */
export function instanceOfDailyQueryCount(value: object): value is DailyQueryCount {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function DailyQueryCountFromJSON(json: any): DailyQueryCount {
    return DailyQueryCountFromJSONTyped(json, false);
}

export function DailyQueryCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyQueryCount {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'count': json['count'],
    };
}

export function DailyQueryCountToJSON(json: any): DailyQueryCount {
    return DailyQueryCountToJSONTyped(json, false);
}

export function DailyQueryCountToJSONTyped(value?: DailyQueryCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'count': value['count'],
    };
}

