/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyQueryCount } from './DailyQueryCount';
import {
    DailyQueryCountFromJSON,
    DailyQueryCountFromJSONTyped,
    DailyQueryCountToJSON,
    DailyQueryCountToJSONTyped,
} from './DailyQueryCount';
import type { ConnectorUsage } from './ConnectorUsage';
import {
    ConnectorUsageFromJSON,
    ConnectorUsageFromJSONTyped,
    ConnectorUsageToJSON,
    ConnectorUsageToJSONTyped,
} from './ConnectorUsage';

/**
 * 
 * @export
 * @interface DashboardStats
 */
export interface DashboardStats {
    /**
     * 
     * @type {number}
     * @memberof DashboardStats
     */
    activeConnectors: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardStats
     */
    queriesUsedThisMonth: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardStats
     */
    queriesLimit: number;
    /**
     * 
     * @type {Array<DailyQueryCount>}
     * @memberof DashboardStats
     */
    queriesPerDay: Array<DailyQueryCount>;
    /**
     * 
     * @type {Array<ConnectorUsage>}
     * @memberof DashboardStats
     */
    mostUsedConnectors: Array<ConnectorUsage>;
    /**
     * 
     * @type {Date}
     * @memberof DashboardStats
     */
    fetchedAt: Date;
}

/**
 * Check if a given object implements the DashboardStats interface.
 */
export function instanceOfDashboardStats(value: object): value is DashboardStats {
    if (!('activeConnectors' in value) || value['activeConnectors'] === undefined) return false;
    if (!('queriesUsedThisMonth' in value) || value['queriesUsedThisMonth'] === undefined) return false;
    if (!('queriesLimit' in value) || value['queriesLimit'] === undefined) return false;
    if (!('queriesPerDay' in value) || value['queriesPerDay'] === undefined) return false;
    if (!('mostUsedConnectors' in value) || value['mostUsedConnectors'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function DashboardStatsFromJSON(json: any): DashboardStats {
    return DashboardStatsFromJSONTyped(json, false);
}

export function DashboardStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardStats {
    if (json == null) {
        return json;
    }
    return {
        
        'activeConnectors': json['active_connectors'],
        'queriesUsedThisMonth': json['queries_used_this_month'],
        'queriesLimit': json['queries_limit'],
        'queriesPerDay': ((json['queries_per_day'] as Array<any>).map(DailyQueryCountFromJSON)),
        'mostUsedConnectors': ((json['most_used_connectors'] as Array<any>).map(ConnectorUsageFromJSON)),
        'fetchedAt': (new Date(json['fetched_at'])),
    };
}

export function DashboardStatsToJSON(json: any): DashboardStats {
    return DashboardStatsToJSONTyped(json, false);
}

export function DashboardStatsToJSONTyped(value?: DashboardStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_connectors': value['activeConnectors'],
        'queries_used_this_month': value['queriesUsedThisMonth'],
        'queries_limit': value['queriesLimit'],
        'queries_per_day': ((value['queriesPerDay'] as Array<any>).map(DailyQueryCountToJSON)),
        'most_used_connectors': ((value['mostUsedConnectors'] as Array<any>).map(ConnectorUsageToJSON)),
        'fetched_at': value['fetchedAt'].toISOString(),
    };
}

