/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryHistoryItem } from './QueryHistoryItem';
import {
    QueryHistoryItemFromJSON,
    QueryHistoryItemFromJSONTyped,
    QueryHistoryItemToJSON,
    QueryHistoryItemToJSONTyped,
} from './QueryHistoryItem';

/**
 * 
 * @export
 * @interface PaginatedQueries
 */
export interface PaginatedQueries {
    /**
     * 
     * @type {Array<QueryHistoryItem>}
     * @memberof PaginatedQueries
     */
    items: Array<QueryHistoryItem>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedQueries
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedQueries
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedQueries
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedQueries
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PaginatedQueries interface.
 */
export function instanceOfPaginatedQueries(value: object): value is PaginatedQueries {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function PaginatedQueriesFromJSON(json: any): PaginatedQueries {
    return PaginatedQueriesFromJSONTyped(json, false);
}

export function PaginatedQueriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedQueries {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(QueryHistoryItemFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'perPage': json['per_page'],
        'totalPages': json['total_pages'],
    };
}

export function PaginatedQueriesToJSON(json: any): PaginatedQueries {
    return PaginatedQueriesToJSONTyped(json, false);
}

export function PaginatedQueriesToJSONTyped(value?: PaginatedQueries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(QueryHistoryItemToJSON)),
        'total': value['total'],
        'page': value['page'],
        'per_page': value['perPage'],
        'total_pages': value['totalPages'],
    };
}

