/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanResponse
 */
export interface PlanResponse {
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    maxConnections: number;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    maxQueriesMonthly: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlanResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the PlanResponse interface.
 */
export function instanceOfPlanResponse(value: object): value is PlanResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('maxConnections' in value) || value['maxConnections'] === undefined) return false;
    if (!('maxQueriesMonthly' in value) || value['maxQueriesMonthly'] === undefined) return false;
    return true;
}

export function PlanResponseFromJSON(json: any): PlanResponse {
    return PlanResponseFromJSONTyped(json, false);
}

export function PlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'price': json['price'],
        'maxConnections': json['max_connections'],
        'maxQueriesMonthly': json['max_queries_monthly'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function PlanResponseToJSON(json: any): PlanResponse {
    return PlanResponseToJSONTyped(json, false);
}

export function PlanResponseToJSONTyped(value?: PlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'max_connections': value['maxConnections'],
        'max_queries_monthly': value['maxQueriesMonthly'],
        'is_active': value['isActive'],
    };
}

