/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortalResponse
 */
export interface PortalResponse {
    /**
     * 
     * @type {string}
     * @memberof PortalResponse
     */
    url: string;
}

/**
 * Check if a given object implements the PortalResponse interface.
 */
export function instanceOfPortalResponse(value: object): value is PortalResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PortalResponseFromJSON(json: any): PortalResponse {
    return PortalResponseFromJSONTyped(json, false);
}

export function PortalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function PortalResponseToJSON(json: any): PortalResponse {
    return PortalResponseToJSONTyped(json, false);
}

export function PortalResponseToJSONTyped(value?: PortalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

