/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryHistoryItem
 */
export interface QueryHistoryItem {
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    connectorId: string;
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    sqlGenerated: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    answer: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryHistoryItem
     */
    error: string | null;
    /**
     * 
     * @type {Date}
     * @memberof QueryHistoryItem
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the QueryHistoryItem interface.
 */
export function instanceOfQueryHistoryItem(value: object): value is QueryHistoryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('connectorId' in value) || value['connectorId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('sqlGenerated' in value) || value['sqlGenerated'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function QueryHistoryItemFromJSON(json: any): QueryHistoryItem {
    return QueryHistoryItemFromJSONTyped(json, false);
}

export function QueryHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'connectorId': json['connector_id'],
        'question': json['question'],
        'sqlGenerated': json['sql_generated'],
        'answer': json['answer'],
        'error': json['error'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function QueryHistoryItemToJSON(json: any): QueryHistoryItem {
    return QueryHistoryItemToJSONTyped(json, false);
}

export function QueryHistoryItemToJSONTyped(value?: QueryHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'connector_id': value['connectorId'],
        'question': value['question'],
        'sql_generated': value['sqlGenerated'],
        'answer': value['answer'],
        'error': value['error'],
        'created_at': value['createdAt'].toISOString(),
    };
}

