/* tslint:disable */
/* eslint-disable */
/**
 * EasySQL API
 * Conecte seus bancos MySQL, MariaDB ou PostgreSQL e faça perguntas em linguagem natural.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    sqlGenerated: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    answer: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof QueryResponse
     */
    chartConfig: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof QueryResponse
     */
    error: string | null;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof QueryResponse
     */
    resultData?: Array<{ [key: string]: any; }> | null;
    /**
     * 
     * @type {Date}
     * @memberof QueryResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): value is QueryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('sqlGenerated' in value) || value['sqlGenerated'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('chartConfig' in value) || value['chartConfig'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
    return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'question': json['question'],
        'sqlGenerated': json['sql_generated'],
        'answer': json['answer'],
        'chartConfig': json['chart_config'],
        'error': json['error'],
        'resultData': json['result_data'] == null ? undefined : json['result_data'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function QueryResponseToJSON(json: any): QueryResponse {
    return QueryResponseToJSONTyped(json, false);
}

export function QueryResponseToJSONTyped(value?: QueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'question': value['question'],
        'sql_generated': value['sqlGenerated'],
        'answer': value['answer'],
        'chart_config': value['chartConfig'],
        'error': value['error'],
        'result_data': value['resultData'],
        'created_at': value['createdAt'].toISOString(),
    };
}

