/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Regenerate: npm run generate
 */

export interface paths {
  "/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/v1/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserLogin"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TokenResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/auth/register": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserCreate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/auth/refresh": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["TokenResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/auth/me": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
      };
    };
    patch: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["UserUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["UserResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
    delete: {
      responses: {
        204: {
          content: never;
        };
      };
    };
  };
  "/v1/auth/change-password": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ChangePasswordRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": unknown;
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/billing/plans": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["PlanResponse"][];
          };
        };
      };
    };
  };
  "/v1/billing/checkout": {
    post: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["CheckoutResponse"];
          };
        };
      };
    };
  };
  "/v1/billing/portal": {
    post: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["PortalResponse"];
          };
        };
      };
    };
  };
  "/v1/connectors": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ConnectorResponse"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConnectorCreate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ConnectorResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/connectors/{connector_id}": {
    get: {
      parameters: {
        path: {
          connector_id: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ConnectorResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          connector_id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConnectorUpdate"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ConnectorResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          connector_id: string;
        };
      };
      responses: {
        204: {
          content: never;
        };
      };
    };
  };
  "/v1/connectors/test": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConnectorTestRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ConnectorTestResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/dashboard/stats": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["DashboardStats"];
          };
        };
      };
    };
  };
  "/v1/queries": {
    get: {
      parameters: {
        query: {
          page?: number;
          per_page?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["PaginatedQueries"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["QueryRequest"];
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["QueryResponse"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
  "/v1/queries/{query_id}": {
    get: {
      parameters: {
        path: {
          query_id: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["QueryHistoryItem"];
          };
        };
        422: {
          content: {
            "application/json": components["schemas"]["HTTPValidationError"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    CheckoutResponse: {
      url: string;
    };
    ConnectorConfig: {
      dbType: string;
      host: string;
      port: number;
      database: string;
      username: string;
      password: string;
      ssl?: boolean;
    };
    ConnectorCreate: {
      type: string;
      name: string;
      config: components["schemas"]["ConnectorConfig"];
    };
    ConnectorResponse: {
      id: string;
      type: string;
      name: string;
      config: components["schemas"]["ConnectorConfig"];
      status: string;
      createdAt: string;
      updatedAt: string;
    };
    ConnectorTestRequest: {
      connectorId: string;
    };
    ConnectorTestResponse: {
      success: boolean;
      message?: string;
    };
    ConnectorUpdate: {
      name?: string;
      config?: components["schemas"]["ConnectorConfig"];
    };
    ConnectorUsage: {
      connectorId: string;
      queryCount: number;
      lastUsed?: string;
    };
    DailyQueryCount: {
      date: string;
      count: number;
    };
    DashboardStats: {
      totalQueries: number;
      totalConnectors: number;
      dailyQueryCounts: components["schemas"]["DailyQueryCount"][];
      connectorUsages: components["schemas"]["ConnectorUsage"][];
    };
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    PaginatedQueries: {
      items: components["schemas"]["QueryHistoryItem"][];
      total: number;
      page: number;
      perPage: number;
      pages: number;
    };
    PlanResponse: {
      id: string;
      name: string;
      price: number;
      features: string[];
    };
    PortalResponse: {
      url: string;
    };
    QueryHistoryItem: {
      id: string;
      question: string;
      sql: string;
      result?: unknown;
      connectorId: string;
      createdAt: string;
    };
    QueryRequest: {
      connectorId: string;
      question: string;
    };
    QueryResponse: {
      id: string;
      question: string;
      sql: string;
      result?: unknown;
      connectorId: string;
      createdAt: string;
    };
    TokenRefresh: {
      refreshToken: string;
    };
    TokenResponse: {
      accessToken: string;
      refreshToken: string;
      tokenType?: string;
    };
    UserCreate: {
      email: string;
      password: string;
      name?: string;
    };
    UserLogin: {
      email: string;
      password: string;
    };
    UserResponse: {
      id: string;
      email: string;
      name?: string;
      createdAt?: string;
    };
    UserUpdate: {
      email?: string;
      name?: string;
      password?: string;
    };
    ValidationError: {
      loc: (string | number)[];
      msg: string;
      type: string;
    };
  };
}

export type operations = {};

export type external = Record<string, never>;
