/**
 * Auto-generated by openapi-typescript.
 * Do not edit directly — regenerate with: make generate
 */

import createClient from "openapi-fetch";
import type { paths } from "./api-types";

export interface CreateClientOptions {
  baseUrl: string;
  accessToken?: string;
  fetch?: typeof fetch;
}

export function createEasySQLClient(options: CreateClientOptions) {
  const client = createClient<paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
    headers: options.accessToken
      ? { Authorization: `Bearer ${options.accessToken}` }
      : {},
  });

  return {
    // ── Auth ──────────────────────────────────────────────────

    /** POST /v1/auth/register */
    register(
      body: paths["/v1/auth/register"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/auth/register", { body });
    },

    /** POST /v1/auth/login */
    login(
      body: paths["/v1/auth/login"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/auth/login", { body });
    },

    /** POST /v1/auth/refresh */
    refresh(
      body: paths["/v1/auth/refresh"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/auth/refresh", { body });
    },

    /** GET /v1/auth/me */
    me() {
      return client.GET("/v1/auth/me");
    },

    /** DELETE /v1/auth/me */
    deleteMe() {
      return client.DELETE("/v1/auth/me");
    },

    /** PATCH /v1/auth/me */
    updateMe(
      body: paths["/v1/auth/me"]["patch"]["requestBody"]["content"]["application/json"],
    ) {
      return client.PATCH("/v1/auth/me", { body });
    },

    /** POST /v1/auth/change-password */
    changePassword(
      body: paths["/v1/auth/change-password"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/auth/change-password", { body });
    },

    // ── Connectors ────────────────────────────────────────────

    /** GET /v1/connectors */
    listConnectors() {
      return client.GET("/v1/connectors");
    },

    /** POST /v1/connectors */
    createConnector(
      body: paths["/v1/connectors"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/connectors", { body });
    },

    /** POST /v1/connectors/test */
    testConnector(
      body: paths["/v1/connectors/test"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/connectors/test", { body });
    },

    /** GET /v1/connectors/{connector_id} */
    getConnector(params: {
      path: paths["/v1/connectors/{connector_id}"]["get"]["parameters"]["path"];
    }) {
      return client.GET("/v1/connectors/{connector_id}", { params });
    },

    /** DELETE /v1/connectors/{connector_id} */
    deleteConnector(params: {
      path: paths["/v1/connectors/{connector_id}"]["delete"]["parameters"]["path"];
    }) {
      return client.DELETE("/v1/connectors/{connector_id}", { params });
    },

    /** PATCH /v1/connectors/{connector_id} */
    updateConnector(
      body: paths["/v1/connectors/{connector_id}"]["patch"]["requestBody"]["content"]["application/json"],
      params: {
        path: paths["/v1/connectors/{connector_id}"]["patch"]["parameters"]["path"];
      },
    ) {
      return client.PATCH("/v1/connectors/{connector_id}", { body, params });
    },

    /** POST /v1/connectors/{connector_id}/sync */
    syncConnector(params: {
      path: paths["/v1/connectors/{connector_id}/sync"]["post"]["parameters"]["path"];
    }) {
      return client.POST("/v1/connectors/{connector_id}/sync", { params });
    },

    // ── Dashboard ─────────────────────────────────────────────

    /** GET /v1/dashboard/stats */
    dashboardStats() {
      return client.GET("/v1/dashboard/stats");
    },

    // ── Billing ───────────────────────────────────────────────

    /** GET /v1/billing/plan */
    getPlan() {
      return client.GET("/v1/billing/plan");
    },

    /** POST /v1/billing/checkout */
    checkout(params: {
      query: paths["/v1/billing/checkout"]["post"]["parameters"]["query"];
    }) {
      return client.POST("/v1/billing/checkout", { params });
    },

    /** POST /v1/billing/portal */
    portal() {
      return client.POST("/v1/billing/portal");
    },

    // ── Queries ───────────────────────────────────────────────

    /** GET /v1/queries */
    listQueries(params?: {
      query: paths["/v1/queries"]["get"]["parameters"]["query"];
    }) {
      return client.GET("/v1/queries", { params } as any);
    },

    /** POST /v1/queries */
    createQuery(
      body: paths["/v1/queries"]["post"]["requestBody"]["content"]["application/json"],
    ) {
      return client.POST("/v1/queries", { body });
    },

    /** GET /v1/queries/{query_id} */
    getQuery(params: {
      path: paths["/v1/queries/{query_id}"]["get"]["parameters"]["path"];
    }) {
      return client.GET("/v1/queries/{query_id}", { params });
    },

    // ── Health ────────────────────────────────────────────────

    /** GET /health */
    health() {
      return client.GET("/health");
    },

    /** GET /v1/health */
    healthV1() {
      return client.GET("/v1/health");
    },
  };
}

export type EasySQLClient = ReturnType<typeof createEasySQLClient>;
