/**
 * Auto-generated by openapi-typescript.
 * Do not edit directly — regenerate with: make generate
 */

import createClient from "openapi-fetch";
import type { paths } from "./api-types";

export interface CreateClientOptions {
  baseUrl: string;
  accessToken?: string;
  fetch?: typeof fetch;
}

export interface EasySQLClient {
  /** POST /v1/auth/register */
  register(body: paths["/v1/auth/register"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** POST /v1/auth/login */
  login(body: paths["/v1/auth/login"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** POST /v1/auth/refresh */
  refresh(body: paths["/v1/auth/refresh"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** GET /v1/auth/me */
  me(): Promise<any>;
  /** PATCH /v1/auth/me */
  updateMe(body: paths["/v1/auth/me"]["patch"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** DELETE /v1/auth/me */
  deleteMe(): Promise<any>;
  /** POST /v1/auth/change-password */
  changePassword(body: paths["/v1/auth/change-password"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** GET /v1/connectors */
  listConnectors(): Promise<any>;
  /** POST /v1/connectors */
  createConnector(body: paths["/v1/connectors"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** POST /v1/connectors/test */
  testConnector(body: paths["/v1/connectors/test"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** GET /v1/connectors/{connector_id}
   * @example
   * await client.getConnector({ connector_id: "..." }) */
  getConnector(params: paths["/v1/connectors/{connector_id}"]["get"]["parameters"]["path"]): Promise<any>;
  /** PATCH /v1/connectors/{connector_id}
   * @example
   * await client.updateConnector({ connector_id: "..." }) */
  updateConnector(body: paths["/v1/connectors/{connector_id}"]["patch"]["requestBody"]["content"]["application/json"], params: { path: paths["/v1/connectors/{connector_id}"]["patch"]["parameters"]["path"] }): Promise<any>;
  /** DELETE /v1/connectors/{connector_id}
   * @example
   * await client.deleteConnector({ connector_id: "..." }) */
  deleteConnector(params: paths["/v1/connectors/{connector_id}"]["delete"]["parameters"]["path"]): Promise<any>;
  /** POST /v1/connectors/{connector_id}/sync
   * @example
   * await client.syncConnector({ connector_id: "..." }) */
  syncConnector(params: paths["/v1/connectors/{connector_id}/sync"]["post"]["parameters"]["path"]): Promise<any>;
  /** GET /v1/connectors/{connector_id}/schema
   * @example
   * await client.getConnectorSchema({ connector_id: "..." }) */
  getConnectorSchema(params: paths["/v1/connectors/{connector_id}/schema"]["get"]["parameters"]["path"]): Promise<any>;
  /** GET /v1/dashboard/stats */
  dashboardStats(): Promise<any>;
  /** GET /v1/billing/plan */
  getPlan(): Promise<any>;
  /** POST /v1/billing/checkout
   * @example
   * await client.checkout({ price_id: 1 }) */
  checkout(params: paths["/v1/billing/checkout"]["post"]["parameters"]["query"]): Promise<any>;
  /** POST /v1/billing/portal */
  portal(): Promise<any>;
  /** GET /v1/queries
   * @example
   * await client.listQueries({ page: 1, per_page: 1 }) */
  listQueries(params: paths["/v1/queries"]["get"]["parameters"]["query"]): Promise<any>;
  /** POST /v1/queries */
  createQuery(body: paths["/v1/queries"]["post"]["requestBody"]["content"]["application/json"]): Promise<any>;
  /** GET /v1/queries/{query_id}
   * @example
   * await client.getQuery({ query_id: "..." }) */
  getQuery(params: paths["/v1/queries/{query_id}"]["get"]["parameters"]["path"]): Promise<any>;
  /** GET /health */
  healthHealth(): Promise<any>;
  /** GET /v1/health */
  health(): Promise<any>;
}

export function createEasySQLClient(options: CreateClientOptions): EasySQLClient {
  const client = createClient<paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
    headers: options.accessToken
      ? { Authorization: `Bearer ${options.accessToken}` }
      : {},
  });

  return {
    /** POST /v1/auth/register */
    register(body: paths["/v1/auth/register"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/auth/register", { body });
    },

    /** POST /v1/auth/login */
    login(body: paths["/v1/auth/login"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/auth/login", { body });
    },

    /** POST /v1/auth/refresh */
    refresh(body: paths["/v1/auth/refresh"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/auth/refresh", { body });
    },

    /** GET /v1/auth/me */
    me() {
      return client.GET("/v1/auth/me");
    },

    /** PATCH /v1/auth/me */
    updateMe(body: paths["/v1/auth/me"]["patch"]["requestBody"]["content"]["application/json"]) {
      return client.PATCH("/v1/auth/me", { body });
    },

    /** DELETE /v1/auth/me */
    deleteMe() {
      return client.DELETE("/v1/auth/me");
    },

    /** POST /v1/auth/change-password */
    changePassword(body: paths["/v1/auth/change-password"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/auth/change-password", { body });
    },

    /** GET /v1/connectors */
    listConnectors() {
      return client.GET("/v1/connectors");
    },

    /** POST /v1/connectors */
    createConnector(body: paths["/v1/connectors"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/connectors", { body });
    },

    /** POST /v1/connectors/test */
    testConnector(body: paths["/v1/connectors/test"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/connectors/test", { body });
    },

    /** GET /v1/connectors/{connector_id} */
    getConnector(params: paths["/v1/connectors/{connector_id}"]["get"]["parameters"]["path"]) {
      return client.GET("/v1/connectors/{connector_id}", { params: { path: params } });
    },

    /** PATCH /v1/connectors/{connector_id} */
    updateConnector(body: paths["/v1/connectors/{connector_id}"]["patch"]["requestBody"]["content"]["application/json"], params: { path: paths["/v1/connectors/{connector_id}"]["patch"]["parameters"]["path"] }) {
      return client.PATCH("/v1/connectors/{connector_id}", { body, params });
    },

    /** DELETE /v1/connectors/{connector_id} */
    deleteConnector(params: paths["/v1/connectors/{connector_id}"]["delete"]["parameters"]["path"]) {
      return client.DELETE("/v1/connectors/{connector_id}", { params: { path: params } });
    },

    /** POST /v1/connectors/{connector_id}/sync */
    syncConnector(params: paths["/v1/connectors/{connector_id}/sync"]["post"]["parameters"]["path"]) {
      return client.POST("/v1/connectors/{connector_id}/sync", { params: { path: params } });
    },

    /** GET /v1/connectors/{connector_id}/schema */
    getConnectorSchema(params: paths["/v1/connectors/{connector_id}/schema"]["get"]["parameters"]["path"]) {
      return client.GET("/v1/connectors/{connector_id}/schema", { params: { path: params } });
    },

    /** GET /v1/dashboard/stats */
    dashboardStats() {
      return client.GET("/v1/dashboard/stats");
    },

    /** GET /v1/billing/plan */
    getPlan() {
      return client.GET("/v1/billing/plan");
    },

    /** POST /v1/billing/checkout */
    checkout(params: paths["/v1/billing/checkout"]["post"]["parameters"]["query"]) {
      return client.POST("/v1/billing/checkout", { params: { query: params } });
    },

    /** POST /v1/billing/portal */
    portal() {
      return client.POST("/v1/billing/portal");
    },

    /** GET /v1/queries */
    listQueries(params: paths["/v1/queries"]["get"]["parameters"]["query"]) {
      return client.GET("/v1/queries", { params: { query: params } });
    },

    /** POST /v1/queries */
    createQuery(body: paths["/v1/queries"]["post"]["requestBody"]["content"]["application/json"]) {
      return client.POST("/v1/queries", { body });
    },

    /** GET /v1/queries/{query_id} */
    getQuery(params: paths["/v1/queries/{query_id}"]["get"]["parameters"]["path"]) {
      return client.GET("/v1/queries/{query_id}", { params: { path: params } });
    },

    /** GET /health */
    healthHealth() {
      return client.GET("/health");
    },

    /** GET /v1/health */
    health() {
      return client.GET("/v1/health");
    }
  } as EasySQLClient;
}
